### ISSUE TITLE
Support for merging stacktrace of inner exceptions

### ISSUE THREAD

**Issue by petamoriken** [tc39/proposal-error-stacks#22]
Some custom error packages, e.g. [extensible-custom-error](https://github.com/necojackarc/extensible-custom-error) and [trace-error](https://github.com/mathew-kurian/TraceError.js), support for holding inner exceptions and emitting it in stacktrace. Please support this in spec (add to #1 list?).

> If you run:
>
> ```js
> const ExtensibleCustomError = require('extensible-custom-error');
>
> class MyError extends ExtensibleCustomError {}
>
> function throwBuiltinError() {
>   throw new Error('Have withstood Pain to create many Weapons');
> }
>
> function wrapErrorWithMyError() {
>   try {
>     throwBuiltinError();
>   } catch (error) {
>     throw new MyError('Unlimited Blade Works', error);
>   }
> }
>
> function main() {
>   try {
>     wrapErrorWithMyError();
>   } catch (error) {
>     console.log(error);
>   }
> }
>
> main();
> ```
>
> you'll get:
>
> ```bash
> MyError: Unlimited Blade Works
>     at wrapErrorWithMyError (/home/necojackarc/custom_error.js:101:11)
> Error: Have withstood Pain to create many Weapons
>     at throwBuiltinError (/home/necojackarc/custom_error.js:94:9)
>     at wrapErrorWithMyError (/home/necojackarc/custom_error.js:99:5)
>     at main (/home/necojackarc/custom_error.js:107:5)
>     at Object.<anonymous> (/home/necojackarc/custom_error.js:113:1)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
>     at Function.Module.runMain (module.js:693:10)
> ```
https://github.com/necojackarc/extensible-custom-error/blob/master/README.md#wrap-an-error-while-passing-a-new-message

**Comment by ljharb** [comment]
This isn't how any JS engines work - error constructors only take one argument, and there's no such thing as "nested errors".

It's an interesting proposal, but it'd need to be a separate one, since it'd need to change every built-in Error constructor.
