### ISSUE TITLE
Erroneous call to GetStackFrameSpanString with non-existant slot source.[[Span]] in 4.5.

### ISSUE THREAD

**Issue by Hendiadyoin1** [tc39/proposal-error-stacks#43]
In 4 source is guaranteed to be a String, and we try to access its [[Span]] slot, which should actually be accessed from the current frame instead.

**Comment by ljharb** [comment]
This should be closed by 7bd153a77fece3f936f7c51d0d5dfd52fb7d75a8; github must be having problems.
