### ISSUE TITLE
A standard way to extend stack traces

### ISSUE THREAD

**Issue by Silic0nS0ldier** [tc39/proposal-error-stacks#45]
There are occasions where stack traces fail to pinpoint the error source (e.g. `Error` being constructed on a unique code path, rethrowing of `Error` instances). It would be useful if a standard way to augment a stack trace with additional context was available.

A standard here may aid error monitoring tools (e.g. Sentry) which attempt to parse the stack trace to provide a richer debug experience.

### `Error` being constructed on a unique code path

[`trace-unhandled`](https://www.npmjs.com/package/trace-unhandled) can be used to address this issue during development (it is stated as not being for production use). It produces stack traces similar to the following.

```
(node:1234) UnhandledPromiseRejectionWarning
[ Stacktrace altered by https://github.com/grantila/trace-unhandled ]
Error: foo
    ==== Promise at: ==================
    at Promise.then (<anonymous>)
    at Object.<anonymous> (/my/directory/test.js:9:5) 

    ==== Error at: ====================
    at Object.<anonymous> (/my/directory/test.js:1:13)

    ==== Shared trace: ================
    at Module._compile (internal/modules/cjs/loader.js:776:30)
	... more lines below ...
```

The stack trace differs considerably from the normal stack.

```
(node:1234) UnhandledPromiseRejectionWarning: Error: foo
    at Object.<anonymous> (/my/directory/test.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
	... more lines below ...
```

### Rethrowing of `Error` instances

No sample necessary for this scenario. The stack trace will simply not include the rethrow site. There is _some_ overlap with #41 here, perhaps mainly with how the trace should be extended.

**Comment by ljharb** [comment]
I'm not really sure what you mean by a standard way to extend stack traces. Error objects already can have an AggregateError, where you can provide anything you like in the `errors` array.

Either way, this is beyond the scope of this proposal - this proposal's sole and entire goal is to specify the *current* behavior of browsers, while providing robust static methods to access this data. This kind of idea would need to wait for a follow-on proposal, after this one has advanced.
